add Timer
razwan/ts-connect-four pull request #19
Opened 2022-10-24 12:55 UTC by ostanmadalina92

2022-10-24 14:14 UTC, razwan requested changes
Hey @ostanmadalina92! Nice job so far!

I left some comment for you to address, and also, please render the Timer component in the app footer and make styles adjustments if necessary.

2022-10-24 14:14 UTC, razwan commented on src/components/Timer/Timer.tsx
> +  time: number;
`time` doesn't seem to be used anywhere. Might as well just remove it

2022-10-24 14:14 UTC, razwan commented on src/components/Timer/Timer.tsx
> +  },[timeLeft]);
This section of code could use some white space for more readability

2022-10-24 14:14 UTC, razwan commented on src/components/Timer/Timer.tsx
> +      setTimeLeft(() => timeLeft - 1);
This should be
```js
setTimeLeft(() => timeLeft - 1);
```

2022-10-24 14:14 UTC, razwan commented on src/components/Timer/Timer.tsx
> +      setTimeLeft(() => timeLeft - 1);
This should be
```js
setTimeLeft(timeLeft => timeLeft - 1);
```
This way the setInterval would update the state with the proper value, and you won't need `timeLeft` in the dependency array anymore

2022-10-24 14:23 UTC, veresbianca approved these changes

2022-10-24 14:23 UTC, FedoraBianca commented on src/components/Timer/Timer.style.tsx
> +export const TimerRectangle = styled.img`
There's no need to create 'TimerRectangle' if it doesn't add any styles. You can simply use an img element.

2022-10-24 15:42 UTC, razwan commented on src/components/Timer/Timer.tsx
>    },[timeLeft]);
Not needed anymore

2022-10-25 08:31 UTC, razwan approved these changes

2022-10-25 10:25 UTC, merged